export const REPO_OWNER_DATA_GET = "REPO_OWNER_DATA_GET";
export const REPO_OWNER_GET_DATA_FAIL = "REPO_OWNER_GET_DATA_FAIL";
export const REPO_OWNER_GET_DATA_SUCCESS = "REPO_OWNER_GET_DATA_SUCCESS";
