export const AUTHORS_REPO_OWNER_GET = "AUTHORS_REPO_OWNER_GET";
export const AUTHORS_REPO_OWNER_GET_FAIL = "AUTHORS_REPO_OWNER_GET_FAIL";
export const AUTHORS_REPO_OWNER_GET_SUCCESS = "AUTHORS_REPO_OWNER_GET_SUCCESS";